lic class TRIPULANTE
{
    public string Nombre, Sexo, Barco;
    public int telefono, cedula, edad, tiempoEmpresa;
    public Tripulante(string Nombre, string Sexo, int telefono, int cedula, int edad, int tiempoEmpresa){
        this.Nombre = Nombre;
        this.Sexo = Sexo;
        this.telefono = telefono;
        this.cedula = cedula;
        this.edad = edad;
        this.tiempoEmpresa = tiempoEmpresa;

    }
    public void SueldoR(){

    }
    public void mostrar(){
        //?
    }
}